"""Unit tests for the PDF renderers.

The renderers are pure, so these assert on real generated bytes — no database,
no object storage, no mocking.
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from io import BytesIO

from pypdf import PdfReader

from app.services.pdf import (
    DecisionLetterData,
    DeclarationData,
    PartyDetails,
    render_claim_decision_letter,
    render_policy_declaration,
)


def extract_text(pdf: bytes) -> str:
    """Read the rendered text back out of a generated PDF.

    Parsing with a real PDF reader rather than poking at reportlab's content
    streams (which are ASCII85-wrapped Flate) keeps these tests about what the
    reader sees, not about how reportlab happens to encode it.
    """
    reader = PdfReader(BytesIO(pdf))
    return "\n".join(page.extract_text() or "" for page in reader.pages)


def sample_declaration(**overrides) -> DeclarationData:
    defaults = dict(
        policy_number="AUTO-2026-000123",
        policy_type="auto",
        status="active",
        effective_date=date(2026, 1, 1),
        expiration_date=date(2026, 12, 31),
        annual_premium=Decimal("1284.50"),
        payment_frequency="monthly",
        insured=PartyDetails(
            name="Dana Whitfield",
            address_lines=["44 Lakeview Rd", "Cleveland, OH 44114"],
        ),
        coverages=[("Coverage type", "Full Coverage"), ("VIN", "1HGCM82633A004352")],
        installments=[("2026-01-01", "$107.04", "Paid")],
        beneficiaries=[],
    )
    defaults.update(overrides)
    return DeclarationData(**defaults)  # type: ignore[arg-type]


def sample_letter(**overrides) -> DecisionLetterData:
    defaults = dict(
        claim_number="CLM-2026-004521",
        policy_number="AUTO-2026-000123",
        claim_type="auto_collision",
        decision="approved",
        decision_date=date(2026, 6, 15),
        incident_date=date(2026, 6, 1),
        reported_date=date(2026, 6, 3),
        insured=PartyDetails(name="Dana Whitfield"),
        estimated_damage=Decimal("3200.00"),
        approved_amount=Decimal("2950.00"),
    )
    defaults.update(overrides)
    return DecisionLetterData(**defaults)  # type: ignore[arg-type]


# --------------------------------------------------------------------------- #
# Declaration page
# --------------------------------------------------------------------------- #
def test_declaration_produces_a_valid_pdf() -> None:
    pdf = render_policy_declaration(sample_declaration())

    assert pdf.startswith(b"%PDF-")
    assert pdf.rstrip().endswith(b"%%EOF")
    assert len(pdf) > 1000


def test_declaration_includes_policy_and_insured_details() -> None:
    text = extract_text(render_policy_declaration(sample_declaration()))

    assert "AUTO-2026-000123" in text
    assert "Dana Whitfield" in text
    assert "1,284.50" in text
    assert "Policy Declaration Page" in text


def test_declaration_renders_deterministically() -> None:
    # Same input must produce the same document, apart from PDF metadata that
    # embeds a timestamp; comparing page text keeps the check meaningful.
    first = extract_text(render_policy_declaration(sample_declaration()))
    second = extract_text(render_policy_declaration(sample_declaration()))

    assert first == second


def test_declaration_omits_beneficiary_section_for_auto() -> None:
    text = extract_text(render_policy_declaration(sample_declaration()))
    assert "Beneficiaries" not in text


def test_declaration_shows_beneficiaries_for_life() -> None:
    data = sample_declaration(
        policy_type="life",
        policy_number="LIFE-2026-000045",
        beneficiaries=[("Jordan Whitfield", "Spouse", "100%")],
        coverages=[("Coverage amount", "$500,000.00")],
    )
    text = extract_text(render_policy_declaration(data))

    assert "Beneficiaries" in text
    assert "Jordan Whitfield" in text


def test_declaration_handles_a_policy_with_no_optional_sections() -> None:
    data = sample_declaration(coverages=[], installments=[], beneficiaries=[])
    pdf = render_policy_declaration(data)

    assert pdf.startswith(b"%PDF-")


# --------------------------------------------------------------------------- #
# Claim decision letter
# --------------------------------------------------------------------------- #
def test_approval_letter_states_the_approved_amount() -> None:
    text = extract_text(render_claim_decision_letter(sample_letter()))

    assert "CLM-2026-004521" in text
    assert "2,950.00" in text
    assert "approved" in text.lower()


def test_rejection_letter_gives_the_reason_and_appeal_rights() -> None:
    data = sample_letter(
        decision="rejected",
        approved_amount=None,
        reason="Damage predates the policy effective date.",
    )
    text = extract_text(render_claim_decision_letter(data))

    assert "Damage predates the policy effective date." in text
    assert "30" in text
    assert "dispute" in text.lower()


def test_rejection_letter_falls_back_when_no_reason_recorded() -> None:
    data = sample_letter(decision="rejected", approved_amount=None, reason=None)
    text = extract_text(render_claim_decision_letter(data))

    assert "not covered" in text.lower()


def test_letter_signs_off_with_the_adjuster_when_known() -> None:
    text = extract_text(render_claim_decision_letter(sample_letter(adjuster_name="Sam Ortiz")))
    assert "Sam Ortiz" in text


def test_letter_signs_off_with_the_department_when_unassigned() -> None:
    text = extract_text(render_claim_decision_letter(sample_letter(adjuster_name=None)))
    assert "Claims Department" in text
