"""Claim decision letter — issued when an adjuster approves or rejects a claim."""

from __future__ import annotations

from decimal import Decimal

from reportlab.platypus import Flowable, Paragraph

from app.services.pdf.content import DecisionLetterData
from app.services.pdf.layout import (
    BODY,
    HEADING,
    SMALL,
    SUBTITLE,
    TITLE,
    build_pdf,
    key_value_table,
    letterhead,
    spacer,
)

APPEAL_WINDOW_DAYS = 30


def _money(value: Decimal | None) -> str:
    if value is None:
        return "—"
    return f"${value:,.2f}"


def _humanize(value: str) -> str:
    return value.replace("_", " ").title()


def _approval_body(data: DecisionLetterData) -> list[str]:
    return [
        f"We have completed our review of claim {data.claim_number} under policy "
        f"{data.policy_number} and are pleased to advise that your claim has been "
        f"<b>approved</b> in the amount of <b>{_money(data.approved_amount)}</b>.",
        "Payment will be issued to the named insured using the disbursement "
        "method on file. You will receive a separate payment confirmation once "
        "the funds have been released.",
        "If you believe the approved amount does not reflect the full extent of "
        "the covered loss, you may submit supporting documentation for "
        "reconsideration through your online account.",
    ]


def _rejection_body(data: DecisionLetterData) -> list[str]:
    reason = data.reason or "The loss reported is not covered under this policy."
    return [
        f"We have completed our review of claim {data.claim_number} under policy "
        f"{data.policy_number}. After careful consideration, we are unable to "
        f"approve this claim.",
        f"<b>Reason for this decision:</b> {reason}",
        f"If you disagree with this determination, you may dispute it within "
        f"{APPEAL_WINDOW_DAYS} days of the date of this letter through your "
        f"online account. A claims manager will review the file independently, "
        f"including any additional documentation you provide.",
    ]


def render_claim_decision_letter(data: DecisionLetterData) -> bytes:
    approved = data.decision == "approved"
    title = "Claim Approval Notice" if approved else "Claim Decision Notice"

    story: list[Flowable] = [
        letterhead(title, "Claim", data.claim_number),
        Paragraph(title, TITLE),
        Paragraph(
            f"{_humanize(data.claim_type)} · Decision issued "
            f"{data.decision_date.isoformat()}",
            SUBTITLE,
        ),
        spacer(6),
    ]

    insured_lines = [data.insured.name, *data.insured.address_lines]
    story.append(Paragraph("<br/>".join(line for line in insured_lines if line), BODY))
    story.append(spacer(4))
    story.append(Paragraph(f"Dear {data.insured.name},", BODY))

    paragraphs = _approval_body(data) if approved else _rejection_body(data)
    story.extend(Paragraph(text, BODY) for text in paragraphs)

    story.append(Paragraph("Claim Summary", HEADING))
    summary = [
        ("Claim number", data.claim_number),
        ("Policy number", data.policy_number),
        ("Claim type", _humanize(data.claim_type)),
        ("Date of loss", data.incident_date.isoformat()),
        ("Date reported", data.reported_date.isoformat()),
        ("Estimated damage", _money(data.estimated_damage)),
    ]
    if approved:
        summary.append(("Approved amount", _money(data.approved_amount)))
    summary.append(("Decision", _humanize(data.decision)))
    story.append(key_value_table(summary))

    story.append(spacer(14))
    story.append(Paragraph("Sincerely,", BODY))
    story.append(
        Paragraph(
            f"{data.adjuster_name or 'Claims Department'}<br/>Claims Department",
            BODY,
        )
    )

    story.append(spacer(12))
    story.append(
        Paragraph(
            "This letter is a demonstration document generated by a portfolio "
            "application. It does not constitute a real claim determination and "
            "no coverage is provided.",
            SMALL,
        )
    )

    return build_pdf(story, title=f"{title} {data.claim_number}")
