"""Policy declaration page — the summary document issued when a policy binds."""

from __future__ import annotations

from decimal import Decimal

from reportlab.platypus import Flowable, Paragraph

from app.services.pdf.content import DeclarationData
from app.services.pdf.layout import (
    BODY,
    HEADING,
    SMALL,
    SUBTITLE,
    TITLE,
    build_pdf,
    column_table,
    key_value_table,
    letterhead,
    spacer,
)


def _money(value: Decimal | None) -> str:
    if value is None:
        return "—"
    return f"${value:,.2f}"


def _humanize(value: str) -> str:
    return value.replace("_", " ").title()


def render_policy_declaration(data: DeclarationData) -> bytes:
    story: list[Flowable] = [
        letterhead("Policy Declaration Page", "Policy", data.policy_number),
        Paragraph("Policy Declaration Page", TITLE),
        Paragraph(
            f"{_humanize(data.policy_type)} insurance · "
            f"Policy status: {_humanize(data.status)}",
            SUBTITLE,
        ),
        spacer(6),
    ]

    story.append(Paragraph("Named Insured", HEADING))
    insured_lines = [data.insured.name, *data.insured.address_lines]
    story.append(Paragraph("<br/>".join(line for line in insured_lines if line), BODY))

    story.append(Paragraph("Policy Period &amp; Premium", HEADING))
    story.append(
        key_value_table(
            [
                ("Policy number", data.policy_number),
                ("Effective date", data.effective_date.isoformat()),
                ("Expiration date", data.expiration_date.isoformat()),
                ("Annual premium", _money(data.annual_premium)),
                ("Payment frequency", _humanize(data.payment_frequency)),
            ]
        )
    )

    if data.coverages:
        story.append(Paragraph("Coverages &amp; Limits", HEADING))
        story.append(
            column_table(
                ["Coverage", "Limit / Detail"],
                [[label, value] for label, value in data.coverages],
            )
        )

    if data.beneficiaries:
        story.append(Paragraph("Beneficiaries", HEADING))
        story.append(
            column_table(
                ["Name", "Relationship", "Allocation"],
                [list(row) for row in data.beneficiaries],
                align_right=(2,),
            )
        )

    if data.installments:
        story.append(Paragraph("Premium Payment Schedule", HEADING))
        story.append(
            column_table(
                ["Due date", "Amount", "Status"],
                [list(row) for row in data.installments],
                align_right=(1,),
            )
        )

    story.append(spacer(16))
    story.append(
        Paragraph(
            "This declaration page summarizes the coverage in force and replaces "
            "any declaration previously issued for this policy. It is subject to "
            "the terms, conditions, and exclusions of the full policy contract. "
            "This is a demonstration document generated by a portfolio "
            "application and is not a contract of insurance.",
            SMALL,
        )
    )

    return build_pdf(story, title=f"Declaration {data.policy_number}")
